pimcore:
  targeting:
    conditions:
      abcondition: ABTargetingBundle\Targeting\Condition\ABCondition

    action_handlers:
      abactionhandler: ABTargetingBundle\Targeting\ActionHandler\ABActionHandler